const ActionTypes = {
  CHANGE_TYPE: 'CHANGE_TYPE',
  ADD_ALL_QUIZZES: 'ADD_ALL_QUIZZES',
  SET_CURRENT_QUIZ: 'SET_CURRENT_QUIZ',
  SET_CURRENT_QUESTION_INDEX: 'SET_CURRENT_QUESTION_INDEX',
  UPDATE_RADIO_BOOL: 'UPDATE_RADIO_BOOL',
  UPDATE_CHECK: 'UPDATE_CHECK',
  UPDATE_BLANK: 'UPDATE_BLANK',
  RESET_STATE: 'RESET_STATE',
};
export default ActionTypes;
